package gui;

public class SegretarioGUI extends javax.swing.JFrame {

    /**
     * Creates new form SegretarioGUI
     */
    private String titolo, descrizione, rivolto, evento, altroevento, titoloDomanda, MaxCharLibera,tipoDomanda; 
    private String sr1,sr2,sr3,sr4,sr5,sr6;
    private String valMaxRange, valMinRange,descValMinRange,descValMAxRange, opzione1,opzione2,opzione3,opzione4,opzione5,opzione6;
    private boolean obbligatorio;
    
    
    public SegretarioGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        InsDatiSondaggio = new javax.swing.JDialog();
        titoloText = new javax.swing.JTextField();
        descrizionetext = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        eventoText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        altroText = new javax.swing.JTextField();
        rivoltoCombo = new javax.swing.JComboBox();
        prosegui = new javax.swing.JButton();
        annullaInsDatiSondaggio = new javax.swing.JButton();
        SceltaDomanda = new javax.swing.JDialog();
        jButton7 = new javax.swing.JButton();
        sceltaDomandaCombo = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        Libera = new javax.swing.JDialog();
        titoloLibera = new javax.swing.JTextField();
        nMaxCharLibera = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        salvaLibera = new javax.swing.JButton();
        annullaLibera = new javax.swing.JButton();
        obbligatoriaLiberaCheck = new javax.swing.JCheckBox();
        Matrice = new javax.swing.JDialog();
        jLabel19 = new javax.swing.JLabel();
        titoloMaticeText = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        vm1Text = new javax.swing.JTextField();
        vm2Text = new javax.swing.JTextField();
        vm3Text = new javax.swing.JTextField();
        vm4Text = new javax.swing.JTextField();
        salvaMatrice = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        sr1Text = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        vm5Text = new javax.swing.JTextField();
        vm6Text = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        sr2Text = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        sr3Text = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        sr4Text = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        sr5Text = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        sr6Text = new javax.swing.JTextField();
        annullaMatrice = new javax.swing.JButton();
        obbligatoriaMatriceCheck = new javax.swing.JCheckBox();
        Range = new javax.swing.JDialog();
        titoloRangeText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        valMinRangeText = new javax.swing.JTextField();
        valMaxRangeText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        descValMinText = new javax.swing.JTextField();
        descValMaxText = new javax.swing.JTextField();
        salvaRange = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        range1Text = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        range2Text = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        range3Text = new javax.swing.JTextField();
        range4Text = new javax.swing.JTextField();
        range5Text = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        annullaRange = new javax.swing.JButton();
        obbligatoriaRangeCheck = new javax.swing.JCheckBox();
        Multipla = new javax.swing.JDialog();
        jLabel14 = new javax.swing.JLabel();
        salvaMultipla = new javax.swing.JButton();
        titoloMultipla = new javax.swing.JTextField();
        multipla1 = new javax.swing.JTextField();
        multipla2 = new javax.swing.JTextField();
        multipla3 = new javax.swing.JTextField();
        multipla4 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        annullaMultipla = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        multipla5 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        multipla6 = new javax.swing.JTextField();
        obbligatoriaMultiplaCheck = new javax.swing.JCheckBox();
        ModificaDomanda = new javax.swing.JDialog();
        modificaDomanda = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        Uscita = new javax.swing.JDialog();
        jLabel38 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        Errore = new javax.swing.JDialog();
        jLabel39 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        visualizzaSondaggio = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton17 = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        InsDatiSondaggio.setTitle("Poll Manager-Crea Sondaggio");
        InsDatiSondaggio.setMinimumSize(new java.awt.Dimension(640, 360));

        jLabel1.setText("Titolo");

        jLabel2.setText("Descrizione");

        jLabel3.setText("Evento");

        jLabel4.setText("Rivolto a...");

        altroText.setEnabled(false);

        rivoltoCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Studenti Polimi", "Studenti Scuole Superiori", "Laureati", "Altro (specificare)..." }));
        rivoltoCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rivoltoComboItemStateChanged(evt);
            }
        });

        prosegui.setLabel("Prosegui...");
        prosegui.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                proseguiMouseClicked(evt);
            }
        });
        prosegui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proseguiActionPerformed(evt);
            }
        });

        annullaInsDatiSondaggio.setLabel("Annulla");
        annullaInsDatiSondaggio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                annullaInsDatiSondaggioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout InsDatiSondaggioLayout = new javax.swing.GroupLayout(InsDatiSondaggio.getContentPane());
        InsDatiSondaggio.getContentPane().setLayout(InsDatiSondaggioLayout);
        InsDatiSondaggioLayout.setHorizontalGroup(
            InsDatiSondaggioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InsDatiSondaggioLayout.createSequentialGroup()
                .addGroup(InsDatiSondaggioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InsDatiSondaggioLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(InsDatiSondaggioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(66, 66, 66)
                        .addGroup(InsDatiSondaggioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(descrizionetext)
                            .addComponent(eventoText)
                            .addComponent(rivoltoCombo, 0, 127, Short.MAX_VALUE)
                            .addComponent(titoloText))
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InsDatiSondaggioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(prosegui)
                        .addGap(155, 155, 155)))
                .addGroup(InsDatiSondaggioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(altroText)
                    .addComponent(annullaInsDatiSondaggio, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        InsDatiSondaggioLayout.setVerticalGroup(
            InsDatiSondaggioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InsDatiSondaggioLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(InsDatiSondaggioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titoloText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(InsDatiSondaggioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descrizionetext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(InsDatiSondaggioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eventoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(29, 29, 29)
                .addGroup(InsDatiSondaggioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rivoltoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(altroText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(InsDatiSondaggioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prosegui)
                    .addComponent(annullaInsDatiSondaggio))
                .addGap(54, 54, 54))
        );

        SceltaDomanda.setTitle("Seleziona Domanda");
        SceltaDomanda.setMaximumSize(new java.awt.Dimension(320, 180));
        SceltaDomanda.setMinimumSize(new java.awt.Dimension(320, 180));
        SceltaDomanda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SceltaDomandaMouseClicked(evt);
            }
        });

        jButton7.setText("Avanti >");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        sceltaDomandaCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Libera", "Multipla", "Matrice", "Range" }));

        jLabel5.setText("Scegli il tipo di domanda:");

        javax.swing.GroupLayout SceltaDomandaLayout = new javax.swing.GroupLayout(SceltaDomanda.getContentPane());
        SceltaDomanda.getContentPane().setLayout(SceltaDomandaLayout);
        SceltaDomandaLayout.setHorizontalGroup(
            SceltaDomandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SceltaDomandaLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(SceltaDomandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sceltaDomandaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        SceltaDomandaLayout.setVerticalGroup(
            SceltaDomandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SceltaDomandaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(sceltaDomandaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        Libera.setMaximumSize(new java.awt.Dimension(600, 320));
        Libera.setMinimumSize(new java.awt.Dimension(600, 320));

        jLabel6.setText("Testo Domanda:");

        jLabel7.setText("Numero massimo caratteri:");

        salvaLibera.setText("Salva");
        salvaLibera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salvaLiberaMouseClicked(evt);
            }
        });

        annullaLibera.setText("Annulla");
        annullaLibera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annullaLiberaActionPerformed(evt);
            }
        });

        obbligatoriaLiberaCheck.setText("Obbligatoria");

        javax.swing.GroupLayout LiberaLayout = new javax.swing.GroupLayout(Libera.getContentPane());
        Libera.getContentPane().setLayout(LiberaLayout);
        LiberaLayout.setHorizontalGroup(
            LiberaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LiberaLayout.createSequentialGroup()
                .addGroup(LiberaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LiberaLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(salvaLibera, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LiberaLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(LiberaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(LiberaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(LiberaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(titoloLibera, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(annullaLibera, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LiberaLayout.createSequentialGroup()
                        .addComponent(nMaxCharLibera, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(obbligatoriaLiberaCheck)))
                .addGap(168, 168, 168))
        );
        LiberaLayout.setVerticalGroup(
            LiberaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LiberaLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(LiberaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titoloLibera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(55, 55, 55)
                .addGroup(LiberaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nMaxCharLibera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(obbligatoriaLiberaCheck))
                .addGap(48, 48, 48)
                .addGroup(LiberaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvaLibera)
                    .addComponent(annullaLibera))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        Matrice.setMaximumSize(new java.awt.Dimension(860, 500));
        Matrice.setMinimumSize(new java.awt.Dimension(860, 500));

        jLabel19.setText("Titolo");

        jLabel20.setText("Valore Matrice 1");

        jLabel21.setText("Valore Matrice 2");

        jLabel22.setText("Valore Matrice 3");

        jLabel23.setText("Valore Matrice 4");

        salvaMatrice.setText("Salva");
        salvaMatrice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salvaMatriceMouseClicked(evt);
            }
        });
        salvaMatrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvaMatriceActionPerformed(evt);
            }
        });

        jLabel24.setText("Sottorisposta 1");

        jLabel25.setText("Valore Martice 5");

        jLabel26.setText("Valora Matrice 6");

        jLabel27.setText("Sottorisposta 2");

        jLabel28.setText("Sottorisposta 3");

        jLabel29.setText("Sottorisposta 4");

        jLabel30.setText("Sottorisposta 5");

        jLabel31.setText("Sottorisposta 6");

        annullaMatrice.setText("Annulla");
        annullaMatrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annullaMatriceActionPerformed(evt);
            }
        });

        obbligatoriaMatriceCheck.setText("Obbligatoria");

        javax.swing.GroupLayout MatriceLayout = new javax.swing.GroupLayout(Matrice.getContentPane());
        Matrice.getContentPane().setLayout(MatriceLayout);
        MatriceLayout.setHorizontalGroup(
            MatriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MatriceLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(MatriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MatriceLayout.createSequentialGroup()
                        .addComponent(obbligatoriaMatriceCheck)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(MatriceLayout.createSequentialGroup()
                        .addGroup(MatriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(50, 50, 50)
                        .addComponent(titoloMaticeText)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MatriceLayout.createSequentialGroup()
                        .addGroup(MatriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MatriceLayout.createSequentialGroup()
                                .addGap(175, 175, 175)
                                .addGroup(MatriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(vm1Text)
                                    .addComponent(vm2Text)
                                    .addComponent(vm3Text)
                                    .addComponent(vm4Text)
                                    .addComponent(vm5Text)
                                    .addComponent(vm6Text, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(salvaMatrice, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(MatriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(MatriceLayout.createSequentialGroup()
                                .addComponent(annullaMatrice, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MatriceLayout.createSequentialGroup()
                                .addGroup(MatriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(MatriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGap(88, 88, 88)
                                .addGroup(MatriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sr2Text, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(sr1Text, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(sr3Text)
                                    .addComponent(sr4Text)
                                    .addComponent(sr5Text)
                                    .addComponent(sr6Text, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(79, 79, 79))))))
        );
        MatriceLayout.setVerticalGroup(
            MatriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MatriceLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(MatriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(MatriceLayout.createSequentialGroup()
                        .addGroup(MatriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(sr1Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(MatriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(sr2Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(MatriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(sr3Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(MatriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(sr4Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(MatriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(sr5Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(MatriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(sr6Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(MatriceLayout.createSequentialGroup()
                        .addGroup(MatriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(titoloMaticeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(MatriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(vm1Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(MatriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(vm2Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(MatriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(vm3Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(MatriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(vm4Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(MatriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(vm5Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(MatriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(vm6Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(obbligatoriaMatriceCheck)
                .addGap(18, 18, 18)
                .addGroup(MatriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvaMatrice)
                    .addComponent(annullaMatrice))
                .addGap(24, 24, 24))
        );

        Range.setMaximumSize(new java.awt.Dimension(640, 680));
        Range.setMinimumSize(new java.awt.Dimension(640, 680));

        jLabel8.setText("Testo Domanda");

        valMaxRangeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valMaxRangeTextActionPerformed(evt);
            }
        });

        jLabel9.setText("Min Valore Range");

        jLabel10.setText("Massimo Valore Range");

        jLabel11.setText("Descrizione:");

        jLabel12.setText("Descrizione:");

        salvaRange.setText("Salva");
        salvaRange.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salvaRangeMouseClicked(evt);
            }
        });
        salvaRange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvaRangeActionPerformed(evt);
            }
        });

        jLabel13.setText("Sotto Domanda:");

        range1Text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                range1TextKeyPressed(evt);
            }
        });

        jLabel32.setText("Sotto Domanda 2:");

        range2Text.setEnabled(false);
        range2Text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                range2TextKeyPressed(evt);
            }
        });

        jLabel33.setText("Sotto Domanda 3:");

        range3Text.setEnabled(false);
        range3Text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                range3TextKeyPressed(evt);
            }
        });

        range4Text.setEnabled(false);
        range4Text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                range4TextKeyPressed(evt);
            }
        });

        range5Text.setEnabled(false);
        range5Text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                range5TextKeyPressed(evt);
            }
        });

        jLabel34.setText("Sotto Domanda 4:");

        jLabel35.setText("Sotto Domanda 5:");
        jLabel35.setToolTipText("");

        annullaRange.setText("Annulla");
        annullaRange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annullaRangeActionPerformed(evt);
            }
        });

        obbligatoriaRangeCheck.setText("Obbligatoria");

        javax.swing.GroupLayout RangeLayout = new javax.swing.GroupLayout(Range.getContentPane());
        Range.getContentPane().setLayout(RangeLayout);
        RangeLayout.setHorizontalGroup(
            RangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RangeLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(RangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(obbligatoriaRangeCheck)
                    .addGroup(RangeLayout.createSequentialGroup()
                        .addGroup(RangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(annullaRange, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34)
                            .addComponent(jLabel32)
                            .addComponent(jLabel35))
                        .addGap(82, 82, 82)
                        .addGroup(RangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RangeLayout.createSequentialGroup()
                                .addGroup(RangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(valMinRangeText, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(valMaxRangeText, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(RangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addGap(37, 37, 37)
                                .addGroup(RangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(descValMinText, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                    .addComponent(descValMaxText)))
                            .addComponent(titoloRangeText, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(RangeLayout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addGroup(RangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(salvaRange, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(RangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(range2Text)
                                        .addComponent(range3Text)
                                        .addComponent(range4Text)
                                        .addComponent(range5Text)
                                        .addComponent(range1Text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        RangeLayout.setVerticalGroup(
            RangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RangeLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(RangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titoloRangeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(39, 39, 39)
                .addGroup(RangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(valMinRangeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(descValMinText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(RangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valMaxRangeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(descValMaxText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(obbligatoriaRangeCheck)
                .addGap(15, 15, 15)
                .addGroup(RangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvaRange)
                    .addComponent(annullaRange))
                .addGap(44, 44, 44)
                .addGroup(RangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(range1Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(RangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(range2Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addGap(18, 18, 18)
                .addGroup(RangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(range3Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33))
                .addGap(18, 18, 18)
                .addGroup(RangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(range4Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34))
                .addGap(18, 18, 18)
                .addGroup(RangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(range5Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        Multipla.setAutoRequestFocus(false);
        Multipla.setMinimumSize(new java.awt.Dimension(540, 500));

        jLabel14.setText("Titolo");

        salvaMultipla.setText("Salva");
        salvaMultipla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salvaMultiplaMouseClicked(evt);
            }
        });
        salvaMultipla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvaMultiplaActionPerformed(evt);
            }
        });

        multipla3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                multipla3KeyPressed(evt);
            }
        });

        multipla4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                multipla4KeyPressed(evt);
            }
        });

        jLabel15.setText("Opzione1");

        jLabel16.setText("Opzione2");

        jLabel17.setText("Opzione3");

        jLabel18.setText("Opzione4");

        annullaMultipla.setText("Annulla");
        annullaMultipla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annullaMultiplaActionPerformed(evt);
            }
        });

        jLabel36.setText("Opzione5");

        multipla5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                multipla5KeyPressed(evt);
            }
        });

        jLabel37.setText("Opzione6");

        obbligatoriaMultiplaCheck.setText("Obbligatoria");

        javax.swing.GroupLayout MultiplaLayout = new javax.swing.GroupLayout(Multipla.getContentPane());
        Multipla.getContentPane().setLayout(MultiplaLayout);
        MultiplaLayout.setHorizontalGroup(
            MultiplaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MultiplaLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(MultiplaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel36)
                    .addComponent(jLabel37))
                .addGap(86, 86, 86)
                .addGroup(MultiplaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titoloMultipla, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MultiplaLayout.createSequentialGroup()
                        .addGroup(MultiplaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MultiplaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(multipla1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(multipla2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(multipla3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                .addComponent(multipla4, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(MultiplaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(multipla6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                .addComponent(multipla5, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(76, 76, 76)
                        .addGroup(MultiplaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(annullaMultipla)
                            .addComponent(salvaMultipla, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(obbligatoriaMultiplaCheck))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        MultiplaLayout.setVerticalGroup(
            MultiplaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MultiplaLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(MultiplaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titoloMultipla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGroup(MultiplaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MultiplaLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(MultiplaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(multipla1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(MultiplaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(multipla2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(MultiplaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(multipla3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MultiplaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(obbligatoriaMultiplaCheck)
                        .addGap(44, 44, 44)))
                .addGroup(MultiplaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(multipla4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salvaMultipla))
                .addGap(18, 18, 18)
                .addGroup(MultiplaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36)
                    .addComponent(multipla5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MultiplaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MultiplaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(multipla6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(annullaMultipla))
                    .addComponent(jLabel37))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        ModificaDomanda.setMaximumSize(new java.awt.Dimension(640, 480));
        ModificaDomanda.setMinimumSize(new java.awt.Dimension(640, 480));

        modificaDomanda.setText("Modifica Domanda Selezionata");
        modificaDomanda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modificaDomandaMouseClicked(evt);
            }
        });
        modificaDomanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificaDomandaActionPerformed(evt);
            }
        });

        jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        javax.swing.GroupLayout ModificaDomandaLayout = new javax.swing.GroupLayout(ModificaDomanda.getContentPane());
        ModificaDomanda.getContentPane().setLayout(ModificaDomandaLayout);
        ModificaDomandaLayout.setHorizontalGroup(
            ModificaDomandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModificaDomandaLayout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addGroup(ModificaDomandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ModificaDomandaLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ModificaDomandaLayout.createSequentialGroup()
                        .addComponent(modificaDomanda)
                        .addGap(206, 206, 206))))
        );
        ModificaDomandaLayout.setVerticalGroup(
            ModificaDomandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModificaDomandaLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(modificaDomanda)
                .addGap(60, 60, 60)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        Uscita.setMinimumSize(new java.awt.Dimension(320, 180));

        jLabel38.setText("Sei sicuro di volere uscire?");

        jButton3.setText("Sì");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setText("No");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UscitaLayout = new javax.swing.GroupLayout(Uscita.getContentPane());
        Uscita.getContentPane().setLayout(UscitaLayout);
        UscitaLayout.setHorizontalGroup(
            UscitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UscitaLayout.createSequentialGroup()
                .addGroup(UscitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UscitaLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101)
                        .addComponent(jButton5))
                    .addGroup(UscitaLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel38)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        UscitaLayout.setVerticalGroup(
            UscitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UscitaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel38)
                .addGap(33, 33, 33)
                .addGroup(UscitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton3))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        Errore.setMinimumSize(new java.awt.Dimension(320, 180));

        jLabel39.setText("Uno o più campi sono non validi o incompleti");

        jButton6.setText("OK");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ErroreLayout = new javax.swing.GroupLayout(Errore.getContentPane());
        Errore.getContentPane().setLayout(ErroreLayout);
        ErroreLayout.setHorizontalGroup(
            ErroreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ErroreLayout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ErroreLayout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addComponent(jLabel39)
                .addGap(93, 93, 93))
        );
        ErroreLayout.setVerticalGroup(
            ErroreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ErroreLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel39)
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Poll Manager- Segretario");
        setForeground(java.awt.Color.white);

        jButton1.setText("Crea Sondaggio");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Modifica Sondaggio");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        visualizzaSondaggio.setText("Visualizza Sondaggio");
        visualizzaSondaggio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                visualizzaSondaggioMouseClicked(evt);
            }
        });

        jButton4.setText("Storicizza\\Destoricizza");

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jButton17.setText("Compila Sondaggio");
        jButton17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton17MouseClicked(evt);
            }
        });

        Logout.setText("Logout");
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem2.setText("Esci");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("?");

        jMenuItem3.setText("About...");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(visualizzaSondaggio)
                        .addGap(27, 27, 27)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(visualizzaSondaggio)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton17))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(Logout)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("Segretario");

        pack();
    }// </editor-fold>                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        ModificaDomanda.setVisible(true);
    }                                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        
    }                                        

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {                                      
        InsDatiSondaggio.setVisible(true);
        // TODO add your handling code here:
    }                                     

    private void proseguiActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        titolo=titoloText.getText().toUpperCase();
        descrizione=descrizionetext.getText().toUpperCase();
        rivolto=(String)rivoltoCombo.getSelectedItem();
        rivolto=rivolto.toUpperCase();
        altroevento=altroText.getText().toUpperCase();
        SceltaDomanda.setVisible(true);
        InsDatiSondaggio.setVisible(false);
        titoloText.setText("");
        descrizionetext.setText("");
        rivoltoCombo.setSelectedIndex(0);
        altroText.setText("");
    }                                        

    private void proseguiMouseClicked(java.awt.event.MouseEvent evt) {                                      
        
    }                                     

    private void valMaxRangeTextActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        if ((String)sceltaDomandaCombo.getSelectedItem()=="Libera"){
            Libera.setVisible(true);
        }
        if ((String)sceltaDomandaCombo.getSelectedItem()=="Matrice"){
            Matrice.setVisible(true);
        }
        if ((String)sceltaDomandaCombo.getSelectedItem()=="Multipla"){
            Multipla.setVisible(true);
        
        }
        if ((String)sceltaDomandaCombo.getSelectedItem()=="Range"){
            Range.setVisible(true);
        }
        
    }                                        

    private void SceltaDomandaMouseClicked(java.awt.event.MouseEvent evt) {                                           
        // TODO add your handling code here:
       
    }                                          

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
        
        
    }                                     

    private void visualizzaSondaggioMouseClicked(java.awt.event.MouseEvent evt) {                                                 

        VisualizzaSondaggioGUI a= new VisualizzaSondaggioGUI();
        a.setVisible(true);
        
        // TODO add your handling code here:
    }                                                

    private void rivoltoComboItemStateChanged(java.awt.event.ItemEvent evt) {                                              
        // TODO add your handling code here:
        
        if (3==rivoltoCombo.getSelectedIndex()) altroText.enable(true);
        else 
        {
            altroText.enable(false);
            altroText.setText("");
        }
        
    }                                             

    private void annullaInsDatiSondaggioMouseClicked(java.awt.event.MouseEvent evt) {                                                     
        // TODO add your handling code here:
        
        titoloText.setText("");
        descrizionetext.setText("");
        altroText.setText("");
        eventoText.setText("");
        rivoltoCombo.setSelectedIndex(0);
        InsDatiSondaggio.setVisible(false);
    }                                                    

    private void salvaLiberaMouseClicked(java.awt.event.MouseEvent evt) {                                         
        // TODO add your handling code here:
        titoloDomanda=titoloLibera.getText().toUpperCase();
        MaxCharLibera=nMaxCharLibera.getText();
        obbligatorio=obbligatoriaLiberaCheck.isSelected();
        System.out.println(obbligatorio);
        titoloLibera.setText("");
        nMaxCharLibera.setText("");
        
        if (titoloDomanda.length()==0 || MaxCharLibera.length()==0){
          
            
            Errore.setVisible(true);
            
            
        }
        else{
            //salva
            
            Libera.setVisible(false);
        
        
        }
        
        
    }                                        

    private void salvaMatriceMouseClicked(java.awt.event.MouseEvent evt) {                                          
        // TODO add your handling code here:
        
                  
    }                                         

    private void modificaDomandaMouseClicked(java.awt.event.MouseEvent evt) {                                             
        // TODO add your handling code here:
        
        
    }                                            

    private void range1TextKeyPressed(java.awt.event.KeyEvent evt) {                                      
        // TODO add your handling code here:
        if (range1Text.getText().length()>0)
            range2Text.enable(true);
        if (range1Text.getText().length()==0) {
            range2Text.enable(false);
            range2Text.setText("");
            range3Text.enable(false);
            range3Text.setText("");
            range4Text.enable(false);
            range4Text.setText("");
            range5Text.enable(false);
            range5Text.setText("");
        } 
    }                                     

    private void range2TextKeyPressed(java.awt.event.KeyEvent evt) {                                      
        // TODO add your handling code here:
        if (range2Text.getText().length()>0)
            range3Text.enable(true);
        if (range2Text.getText().length()==0) {
            range3Text.enable(false);
            range3Text.setText("");
            range4Text.enable(false);
            range4Text.setText("");
            range5Text.enable(false);
            range5Text.setText("");
        } 
    }                                     

    private void range3TextKeyPressed(java.awt.event.KeyEvent evt) {                                      
        // TODO add your handling code here:
        if (range3Text.getText().length()>0)
            range4Text.enable(true);
        if (range3Text.getText().length()==0) {
            range4Text.enable(false);
            range4Text.setText("");
            range5Text.enable(false);
            range5Text.setText("");
        } 
    }                                     

    private void range4TextKeyPressed(java.awt.event.KeyEvent evt) {                                      
        // TODO add your handling code here:
        if (range4Text.getText().length()>0)
            range5Text.enable(true);
        if (range4Text.getText().length()==0) {
            range5Text.enable(false);
            range5Text.setText("");
        } 
    }                                     

    private void range5TextKeyPressed(java.awt.event.KeyEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void salvaRangeMouseClicked(java.awt.event.MouseEvent evt) {                                        
        // TODO add your handling code here:
        
        
        
    }                                       

    private void salvaMultiplaMouseClicked(java.awt.event.MouseEvent evt) {                                           
        // TODO add your handling code here:
        
    }                                          

    private void multipla3KeyPressed(java.awt.event.KeyEvent evt) {                                     
        // TODO add your handling code here:
        
        if (multipla1.getText().length()>0 && multipla2.getText().length()>0 && multipla3.getText().length()>0){
            multipla4.enable(true);
        }
        else   {
            multipla4.enable(false);
            multipla4.setText("");
            multipla5.setText("");
            multipla6.setText("");
        }
    }                                    

    private void multipla4KeyPressed(java.awt.event.KeyEvent evt) {                                     
        // TODO add your handling code here:
        if (multipla1.getText().length() > 0 && multipla2.getText().length() > 0 && multipla3.getText().length() > 0 && multipla4.getText().length() > 0) {
            multipla5.enable(true);
        } else {
            multipla5.enable(false);
            multipla5.setText("");
            multipla6.setText("");
        }

    }                                    

    private void multipla5KeyPressed(java.awt.event.KeyEvent evt) {                                     
        // TODO add your handling code here:
        if (multipla1.getText().length()>0 && multipla2.getText().length()>0 && multipla3.getText().length()>0 && multipla4.getText().length()>0 && multipla5.getText().length()>0){
            multipla6.enable(true);
        }
        else  {
            multipla6.enable(false);
            multipla6.setText("");
        }
    }                                    

    private void jButton17MouseClicked(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
        CompilazioneGUI c=new CompilazioneGUI();
        c.setVisible(true);
    }                                      

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {                                    
        // TODO add your handling code here:
        AccessoGUI b=new AccessoGUI();
        this.setVisible(false);
        b.setVisible(true);    
    }                                   

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void annullaLiberaActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        titoloLibera.setText("");
        nMaxCharLibera.setText("");
        obbligatoriaLiberaCheck.setSelected(false);
        Libera.setVisible(false);
    }                                             

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        Uscita.setVisible(true);
    }                                          

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        AboutGUI a= new AboutGUI();
        a.setVisible(true);
    }                                          

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        System.exit((0));
    }                                        

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        Uscita.setVisible(false);
    }                                        

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        Errore.setVisible(false);
    }                                        

    private void annullaRangeActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        titoloRangeText.setText("");
        valMinRangeText.setText("");
        valMaxRangeText.setText("");
        descValMinText.setText("");
        descValMaxText.setText("");
        range1Text.setText("");
        range2Text.setText("");
        range3Text.setText("");
        range4Text.setText("");
        range5Text.setText("");
        obbligatoriaRangeCheck.setSelected(false);
        
        Range.setVisible(false);
    }                                            

    private void salvaRangeActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        titoloDomanda=titoloRangeText.getText();
        valMinRange=valMinRangeText.getText();
        valMaxRange=valMaxRangeText.getText();
        descValMinRange=descValMinText.getText();
        descValMAxRange=descValMaxText.getText();
        opzione1=range1Text.getText();
        opzione2=range2Text.getText();
        opzione3=range3Text.getText();
        opzione4=range4Text.getText();
        opzione5=range5Text.getText();
        obbligatorio=obbligatoriaRangeCheck.isSelected();
        
        try{
            
            if (Integer.parseInt(valMaxRange)<=Integer.parseInt(valMinRange)){
                Errore.setVisible(true);
                valMaxRangeText.setText("");
                valMinRangeText.setText("");
            }
            
            else{
                titoloRangeText.setText("");
                valMinRangeText.setText("");
                valMaxRangeText.setText("");
                descValMinText.setText("");
                descValMaxText.setText("");
                range1Text.setText("");
                range2Text.setText("");
                range3Text.setText("");
                range4Text.setText("");
                range5Text.setText("");
                Range.setVisible(false);
            }
        }
        catch (NumberFormatException e){
            
            Errore.setVisible(true);
            valMaxRangeText.setText("");
            valMinRangeText.setText("");
        }
    }                                          

    private void salvaMatriceActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        titoloDomanda=titoloMaticeText.getText().toUpperCase();
        opzione1=vm1Text.getText().toUpperCase();
        opzione2=vm2Text.getText().toUpperCase();
        opzione3=vm3Text.getText().toUpperCase();
        opzione4=vm4Text.getText().toUpperCase();
        opzione5=vm5Text.getText().toUpperCase();
        opzione6=vm6Text.getText().toUpperCase();
        sr1=sr1Text.getText().toUpperCase();
        sr2=sr2Text.getText().toUpperCase();
        sr3=sr3Text.getText().toUpperCase();
        sr4=sr4Text.getText().toUpperCase();
        sr5=sr5Text.getText().toUpperCase();
        sr6=sr6Text.getText().toUpperCase();
        obbligatorio=obbligatoriaMatriceCheck.isSelected();
        titoloMaticeText.setText("");
        vm1Text.setText("");
        vm2Text.setText("");
        vm3Text.setText("");
        vm4Text.setText("");
        vm5Text.setText("");
        vm6Text.setText("");
        sr1Text.setText("");
        sr2Text.setText("");
        sr3Text.setText("");
        sr4Text.setText("");        
        sr5Text.setText("");
        sr6Text.setText("");
        
        Matrice.setVisible(false);
    }                                            

    private void annullaMatriceActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
        titoloMaticeText.setText("");
        vm1Text.setText("");
        vm2Text.setText("");
        vm3Text.setText("");
        vm4Text.setText("");
        vm5Text.setText("");
        vm6Text.setText("");
        sr1Text.setText("");
        sr2Text.setText("");
        sr3Text.setText("");
        sr4Text.setText("");        
        sr5Text.setText("");
        sr6Text.setText("");
        obbligatoriaMatriceCheck.setSelected(false);
        Matrice.setVisible(false);
    }                                              

    private void annullaMultiplaActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
        
        titoloMultipla.setText("");
        multipla1.setText("");
        multipla2.setText("");
        multipla3.setText("");
        multipla4.setText("");
        multipla5.setText("");
        multipla6.setText("");
        obbligatoriaMultiplaCheck.setSelected(false);
        
        
        Multipla.setVisible(false);
    }                                               

    private void salvaMultiplaActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        titoloDomanda=titoloMultipla.getText();
        opzione1=multipla1.getText();
        opzione2=multipla2.getText();
        opzione3=multipla3.getText();
        opzione4=multipla4.getText();
        opzione5=multipla5.getText();
        opzione6=multipla6.getText(); 
        obbligatorio=obbligatoriaMultiplaCheck.isSelected();
        
        
        titoloMultipla.setText("");
        multipla1.setText("");
        multipla2.setText("");
        multipla3.setText("");
        multipla4.setText("");
        multipla5.setText("");
        multipla6.setText("");
        
        Multipla.setVisible(false);
    }                                             

    private void modificaDomandaActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
        if (tipoDomanda=="Libera"){
            Libera.setVisible(true);
           
            ////compilo text
        }
        if (tipoDomanda=="Matrice"){
            Matrice.setVisible(true);
            
            ////compilo text
        }
        if (tipoDomanda=="Multipla"){
            Multipla.setVisible(true);
            ////compilo text
        
        }
        if (tipoDomanda=="Range"){
            Range.setVisible(true);
            
            ////compilo text
        }
    }                                               

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SegretarioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SegretarioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SegretarioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SegretarioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new SegretarioGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify                     
    private javax.swing.JDialog Errore;
    private javax.swing.JDialog InsDatiSondaggio;
    private javax.swing.JDialog Libera;
    private javax.swing.JButton Logout;
    private javax.swing.JDialog Matrice;
    private javax.swing.JDialog ModificaDomanda;
    private javax.swing.JDialog Multipla;
    private javax.swing.JDialog Range;
    private javax.swing.JDialog SceltaDomanda;
    private javax.swing.JDialog Uscita;
    private javax.swing.JTextField altroText;
    private javax.swing.JButton annullaInsDatiSondaggio;
    private javax.swing.JButton annullaLibera;
    private javax.swing.JButton annullaMatrice;
    private javax.swing.JButton annullaMultipla;
    private javax.swing.JButton annullaRange;
    private javax.swing.JTextField descValMaxText;
    private javax.swing.JTextField descValMinText;
    private javax.swing.JTextField descrizionetext;
    private javax.swing.JTextField eventoText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton modificaDomanda;
    private javax.swing.JTextField multipla1;
    private javax.swing.JTextField multipla2;
    private javax.swing.JTextField multipla3;
    private javax.swing.JTextField multipla4;
    private javax.swing.JTextField multipla5;
    private javax.swing.JTextField multipla6;
    private javax.swing.JTextField nMaxCharLibera;
    private javax.swing.JCheckBox obbligatoriaLiberaCheck;
    private javax.swing.JCheckBox obbligatoriaMatriceCheck;
    private javax.swing.JCheckBox obbligatoriaMultiplaCheck;
    private javax.swing.JCheckBox obbligatoriaRangeCheck;
    private javax.swing.JButton prosegui;
    private javax.swing.JTextField range1Text;
    private javax.swing.JTextField range2Text;
    private javax.swing.JTextField range3Text;
    private javax.swing.JTextField range4Text;
    private javax.swing.JTextField range5Text;
    private javax.swing.JComboBox rivoltoCombo;
    private javax.swing.JButton salvaLibera;
    private javax.swing.JButton salvaMatrice;
    private javax.swing.JButton salvaMultipla;
    private javax.swing.JButton salvaRange;
    private javax.swing.JComboBox sceltaDomandaCombo;
    private javax.swing.JTextField sr1Text;
    private javax.swing.JTextField sr2Text;
    private javax.swing.JTextField sr3Text;
    private javax.swing.JTextField sr4Text;
    private javax.swing.JTextField sr5Text;
    private javax.swing.JTextField sr6Text;
    private javax.swing.JTextField titoloLibera;
    private javax.swing.JTextField titoloMaticeText;
    private javax.swing.JTextField titoloMultipla;
    private javax.swing.JTextField titoloRangeText;
    private javax.swing.JTextField titoloText;
    private javax.swing.JTextField valMaxRangeText;
    private javax.swing.JTextField valMinRangeText;
    private javax.swing.JButton visualizzaSondaggio;
    private javax.swing.JTextField vm1Text;
    private javax.swing.JTextField vm2Text;
    private javax.swing.JTextField vm3Text;
    private javax.swing.JTextField vm4Text;
    private javax.swing.JTextField vm5Text;
    private javax.swing.JTextField vm6Text;
    // End of variables declaration                   
}
