package gui;

import java.awt.List;
import java.rmi.RemoteException;

import client.ClientInterface;

import dto.DomandaDTO;
import dto.RispostaDTO;
import dto.SondaggioDTO;
import dto.UtenteDTO;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * 
 * @author Alberto
 */
public class VisualizzaSondaggioGUI extends javax.swing.JFrame {
	private int idSondaggio;
	private ClientInterface client;

	/**
	 * Creates new form VisualizzaSondaggio
	 */
	public VisualizzaSondaggioGUI(int idSondaggio, ClientInterface client) {
		initComponents();
		this.client = client;
		this.idSondaggio = idSondaggio;
		this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	 @SuppressWarnings("unchecked")
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">
	    private void initComponents() {

	        jLabel3 = new javax.swing.JLabel();
	        jButton5 = new javax.swing.JButton();
	        jScrollPane4 = new javax.swing.JScrollPane();
	        jList4 = new javax.swing.JList();
	        jScrollPane5 = new javax.swing.JScrollPane();
	        jList5 = new javax.swing.JList();
	        jLabel4 = new javax.swing.JLabel();
	        visualizzaRisposte = new javax.swing.JButton();

	        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

	        jLabel3.setText("Risposte:");

	        jButton5.setText("Chiudi");
	        jButton5.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jButton5ActionPerformed(evt);
	            }
	        });

	        jScrollPane4.setViewportView(jList4);

	        jList5.setModel(new javax.swing.AbstractListModel() {
	            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
	            public int getSize() { return strings.length; }
	            public Object getElementAt(int i) { return strings[i]; }
	        });
	        jScrollPane5.setViewportView(jList5);

	        jLabel4.setText("Domande:");

	        visualizzaRisposte.setText("Visualizza Possibili Risposte");
	        visualizzaRisposte.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                visualizzaRisposteActionPerformed(evt);
	            }
	        });

	        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
	        getContentPane().setLayout(layout);
	        layout.setHorizontalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(layout.createSequentialGroup()
	                .addGap(65, 65, 65)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addGroup(layout.createSequentialGroup()
	                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 236, Short.MAX_VALUE)
	                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addGap(156, 156, 156))
	                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
	                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
	                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
	                            .addComponent(visualizzaRisposte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
	                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
	                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	                        .addGap(45, 45, 45))))
	        );
	        layout.setVerticalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(layout.createSequentialGroup()
	                .addGap(24, 24, 24)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jLabel3))
	                .addGap(32, 32, 32)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
	                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jButton5)
	                    .addComponent(visualizzaRisposte))
	                .addGap(21, 21, 21))
	        );

	        pack();
	    }// </editor-fold>


	 /**
	  * Chiude VisualizzaSondaggioGUI
	  * @param evt
	  */
	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
		this.setVisible(false);
	}
	
	/**
	 * Stampa la lista risposte della domanda selezionata
	 * @param evt 
	 */
	private void visualizzaRisposteActionPerformed(java.awt.event.ActionEvent evt) {
		
		java.util.List<RispostaDTO> listarisposte= (java.util.List<RispostaDTO>)new List();
		int idDomanda = ((DomandaDTO) jList4.getSelectedValue()).getIdDomanda();
		
		//TODO lista risposte
	
	}
	
	/**
     * inizializza VisualizzaSondaggioGUI
     */
	private void inizializza() {

		java.util.List<DomandaDTO> listaDomande = (java.util.List<DomandaDTO>) new List();
		try {

			SondaggioDTO s = client.SondaggioGetByKey(idSondaggio);
			listaDomande = s.getDomande();

		} catch (RemoteException e) {

			e.printStackTrace();
			e.getMessage();
		}
		jList4.setListData(listaDomande.toArray());

	}

	
	private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList jList4;
    private javax.swing.JList jList5;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton visualizzaRisposte;
	
}
